# Generated by Django 4.0.4 on 2022-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0002_sign_delete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='confirmPassword',
            field=models.CharField(default=1, max_length=62),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='password',
            field=models.CharField(default=0, max_length=62),
        ),
    ]
