# Generated by Django 4.0.4 on 2022-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0003_sign_confirmpassword_sign_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='password',
            field=models.CharField(max_length=62),
        ),
    ]
